title: "Lakshminarayanan"
baseurl: ""
url: ""
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
collections:
  microblog:
    output: true
    permalink: /microblog/:title/
  photos:
    output: true
    permalink: /photos/:title/
  work:
    output: false
sass:
  style: compressed
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
      type: "microblog"
    values:
      layout: post
  - scope:
      path: ""
      type: "photos"
    values:
      layout: photo
